# Generated by Django 5.1.7 on 2025-03-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
