# Generated by Django 5.1.7 on 2025-03-22 22:13

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.CharField(
                max_length=10, null=True, validators=[users.models.validate_date_format]
            ),
        ),
    ]
